/**
 * @author            : Priya Soni
 * @last modified on  : 10-07-2024
 * @last modified by  : Priya Soni
**/
// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents

// apex-1011
Assign1011.main();

// apex-1012
Assign1012.main();

// apex-1013
Assign1013.main();

// apex-1014
Assign1014.main();

// apex-1015
Assign1015.main();

// apex-1021
Assign1021.main();

// apex-1022
Assign1022.main();

// apex-1023
Assign1023.main();

// apex-1024
Assign1024.main();

// apex-1025
Assign1025.main();

// apex-1031
Assign1031.main();

// apex-1032
Assign1032.main();

// apex-1033
Assign1033.main();

// apex-1034
Assign1034.main();

// apex-1035
Assign1035.main();

// apex-1041
Assign1041.main();

// apex-1042
Assign1042.main();

// apex-1043
Assign1043.main();

// apex-1044
Assign1044.main();

// apex-1045
Assign1045.main();

// apex-1051
Assign1051.main();

// apex-1052
Assign1052.main();

// apex-1053
Assign1053.main();

// apex-1054
Assign1054.main();

// apex-1055
Assign1055.main();

// apex-1061
Assign1061.main();

// apex-1062
Assign1062.main();

// apex-1063
Assign1063.main();

// apex-1064
Assign1064.main();

// apex-1065
Assign1065.main();

// apex-1071
Assign1071.main();

// apex-1072
Assign1072.main();

// apex-1073
Assign1073.main();

// apex-1074
Assign1074.main();

// apsx-1075
Assign1075.main();
